const projects = [
  {
    name: "D&D Character Creator (MERN Stack)",
    desc: "Full-stack MERN web app with hashed passwords, secure session management, REST API integration, and role-based access control.",
    stack: ["MongoDB", "Express", "React", "Node.js", "JWT"],
    tag: "fullstack",
    link: "https://github.com/michaeljawn/MERNStackWebApp",
  },
  {
    name: "Java Web App with MySQL",
    desc: "Three-tier Java web application with Servlets, JSP, and JDBC on Apache Tomcat. Role-based authentication backed by MySQL.",
    stack: ["Java", "MySQL", "JSP", "Servlets", "Tomcat"],
    tag: "fullstack",
  },
  {
    name: "Prototype Website",
    desc: "Early prototype website demonstrating front-end layout and design skills.",
    stack: ["HTML", "CSS", "JavaScript"],
    tag: "fullstack",
  },
  {
    name: "GoogleMeetWalker",
    desc: "Automation tool for Google Meet sessions.",
    stack: ["JavaScript", "Python"],
    tag: "fullstack",
  },
  {
    name: "Guitar Rave",
    desc: "Music-themed interactive web application.",
    stack: ["JavaScript", "HTML", "CSS"],
    tag: "fullstack",
  },
  {
    name: "MusicApp / BETTERMUSIC",
    desc: "Music player or streaming utility with improved UX.",
    stack: ["JavaScript"],
    tag: "fullstack",
  },
  {
    name: "Webgrabber",
    desc: "Web scraping and data extraction tool.",
    stack: ["Python"],
    tag: "fullstack",
  },
  {
    name: "Pokehelp",
    desc: "Pokémon helper and companion web app.",
    stack: ["JavaScript", "HTML"],
    tag: "fullstack",
  },
  {
    name: "Discord Bot (TS & Python)",
    desc: "Discord bots built in TypeScript and Python with custom commands and automations.",
    stack: ["TypeScript", "Python", "Discord.js"],
    tag: "fullstack",
  },
  {
    name: "GF BOT",
    desc: "Automation bot project.",
    stack: ["Python"],
    tag: "fullstack",
  },
  {
    name: "Async JavaScript & Fetch",
    desc: "Projects demonstrating async JS patterns, promises, and the Fetch API.",
    stack: ["JavaScript"],
    tag: "fullstack",
  },
  {
    name: "DOM Manipulation",
    desc: "Interactive DOM manipulation exercises and web demos.",
    stack: ["JavaScript", "HTML"],
    tag: "fullstack",
  },
  {
    name: "Basic Web (JS / CSS / HTML)",
    desc: "Foundational web development projects covering core web technologies.",
    stack: ["HTML", "CSS", "JavaScript"],
    tag: "fullstack",
  },
  {
    name: "CustomStartPage",
    desc: "Custom browser start page with personalized widgets and quick links.",
    stack: ["HTML", "CSS", "JavaScript"],
    tag: "fullstack",
  },
  {
    name: "Resume.github.io",
    desc: "Personal resume hosted as a GitHub Pages site.",
    stack: ["HTML", "CSS"],
    tag: "fullstack",
  },
  {
    name: "TOI-AD-master",
    desc: "Ad or UI component and interaction project.",
    stack: ["JavaScript", "HTML"],
    tag: "fullstack",
  },
  {
    name: "Home Lab: NAS Server",
    desc: "Built and secured a NAS server with VPN access, disk encryption, and port forwarding for remote access.",
    stack: ["Linux", "VPN", "Networking"],
    tag: "security",
  },
  {
    name: "DLL Hack",
    desc: "DLL injection research and experimentation project.",
    stack: ["C/C++"],
    tag: "security",
  },
  {
    name: "Memory Manipulation Testing",
    desc: "Low-level memory manipulation and testing project.",
    stack: ["C/C++"],
    tag: "security",
  },
  {
    name: "LED Visualizer / audio-reactive-led-strip",
    desc: "Audio-reactive LED strip that responds to music in real-time using frequency analysis.",
    stack: ["Python", "Arduino"],
    tag: "hardware",
  },
  {
    name: "Arduino Package",
    desc: "Collection of Arduino experiments, sketches, and random code projects.",
    stack: ["Arduino", "C++"],
    tag: "hardware",
  },
  {
    name: "Bluetooth Robotics",
    desc: "Bluetooth-controlled robotics project built with Arduino.",
    stack: ["Arduino", "Bluetooth", "C++"],
    tag: "hardware",
  },
  {
    name: "Motor Control",
    desc: "Motor control and automation project using Arduino.",
    stack: ["Arduino", "C++"],
    tag: "hardware",
  },
  {
    name: "LEARN PI",
    desc: "Raspberry Pi learning and experimentation project.",
    stack: ["Python", "Raspberry Pi"],
    tag: "hardware",
  },
  {
    name: "Face Recognition",
    desc: "Face detection and recognition system using computer vision.",
    stack: ["Python", "OpenCV"],
    tag: "ml",
  },
  {
    name: "Speech Detection & Recognition",
    desc: "Real-time speech detection and recognition pipeline with audio processing.",
    stack: ["Python", "ML"],
    tag: "ml",
  },
  {
    name: "TensorFlow Experiments",
    desc: "Machine learning experiments and starter models using TensorFlow.",
    stack: ["Python", "TensorFlow"],
    tag: "ml",
  },
  {
    name: "SoundTracking",
    desc: "Audio analysis and sound tracking application.",
    stack: ["Python"],
    tag: "ml",
  },
  {
    name: "FormCheck AI Application",
    desc: "AI-powered form checking and validation application.",
    stack: ["Python", "AI/ML"],
    tag: "ml",
  },
  {
    name: "Fortnite OCR",
    desc: "OCR tool for reading and parsing Fortnite in-game data.",
    stack: ["Python", "OpenCV", "OCR"],
    tag: "ml",
  },
  {
    name: "Fall Detector",
    desc: "Computer vision system to detect falls in real-time.",
    stack: ["Python", "OpenCV", "ML"],
    tag: "ml",
  },
  {
    name: "Galaga",
    desc: "Recreation of the classic Galaga arcade game.",
    stack: ["Python", "Pygame"],
    tag: "game",
  },
  {
    name: "Snake",
    desc: "Classic Snake game implementation.",
    stack: ["Python", "Pygame"],
    tag: "game",
  },
  {
    name: "Simon",
    desc: "Simon Says memory game with increasing difficulty levels.",
    stack: ["Python"],
    tag: "game",
  },
  {
    name: "Minecraft on Crack",
    desc: "Minecraft-inspired game or mod project.",
    stack: ["Java"],
    tag: "game",
  },
  {
    name: "AnitFunValorant",
    desc: "Valorant-related game utility or fun project.",
    stack: ["Python"],
    tag: "game",
  },
  {
    name: "Windows Sysadmin & PowerShell Lab",
    desc: "Configured Windows Active Directory domain. Automated 5+ admin tasks via PowerShell scripts with Task Scheduler.",
    stack: ["Windows Server", "Active Directory", "PowerShell"],
    tag: "systems",
  },
  {
    name: "AWS SysOps Cloud Ops Lab",
    desc: "Simulated enterprise AWS environment with EC2, IAM, Security Groups, and S3. Least-privilege roles and recovery scenarios.",
    stack: ["AWS", "EC2", "IAM", "S3"],
    tag: "systems",
  },
  {
    name: "Socket Train / Socket_Taze",
    desc: "Socket programming and networking experiments exploring TCP/UDP communication.",
    stack: ["Python", "Networking"],
    tag: "systems",
  },
  {
    name: "Java HTTP",
    desc: "HTTP server and client implementation in Java.",
    stack: ["Java", "HTTP"],
    tag: "systems",
  },
  {
    name: "Computer Logic & Organization",
    desc: "Low-level computing, logic gates, and architecture coursework project.",
    stack: ["Assembly", "C"],
    tag: "systems",
  },
  {
    name: "Python Memory",
    desc: "Python memory management exploration and experiments.",
    stack: ["Python"],
    tag: "systems",
  },
  {
    name: "Funny Mic",
    desc: "Microphone audio effects and real-time voice manipulation tool.",
    stack: ["Python"],
    tag: "other",
  },
  {
    name: "Alarm / Applet",
    desc: "Simple alarm clock desktop applet.",
    stack: ["Java", "Python"],
    tag: "other",
  },
  {
    name: "AudioController",
    desc: "System audio control and management utility.",
    stack: ["Python"],
    tag: "other",
  },
  {
    name: "Nile",
    desc: "JavaScript utility or web project.",
    stack: ["JavaScript"],
    tag: "other",
  },
];

export const TAG_LABELS = {
  fullstack: "Full-stack",
  security: "Security",
  hardware: "Hardware",
  ml: "ML / AI",
  game: "Game",
  systems: "Systems",
  other: "Other",
};

export const FILTERS = ["all", "fullstack", "security", "hardware", "ml", "game", "systems", "other"];

export default projects;
